# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build

    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      if: success()
      with:
        name: Underground City Engineering - 1.0.0
        path: build/libs/Underground City Engineering-1.0.0.jar

    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      if: success()
      with:
        name: Underground City Engineering - 1.0.0 Sources
        path: build/libs/Underground City Engineering-1.0.0-sources.jar